FROM nats-streaming:0.7.0-linux
#COPY /docker/natss/a/gnatsd.conf /tmp/cluster.conf

## Run via the configuration file
#ENTRYPOINT ["/gnatsd"]
#CMD ["-c", "/tmp/cluster.conf"]
#
## Expose client and management ports
#EXPOSE 4222 8222
#
## Run with default memory based store
#ENTRYPOINT ["/nats-streaming-server"]
#CMD ["-m", "8222"]